/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 65
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  aux_sym_object_token1 = 2,
  anon_sym_RBRACE = 3,
  anon_sym_COLON = 4,
  anon_sym_LBRACK = 5,
  anon_sym_RBRACK = 6,
  sym_escape_sequence = 7,
  sym_number = 8,
  sym_true = 9,
  sym_false = 10,
  sym_null = 11,
  sym_comment = 12,
  anon_sym_DQUOTE = 13,
  anon_sym_SQUOTE = 14,
  aux_sym__quoted_string_content_token1 = 15,
  aux_sym_quoteless_string_token1 = 16,
  anon_sym_SQUOTE_SQUOTE_SQUOTE = 17,
  aux_sym_multiline_string_token1 = 18,
  sym_document = 19,
  sym__value = 20,
  sym_object = 21,
  sym_pair = 22,
  sym_array = 23,
  sym_string = 24,
  sym_quoted_string = 25,
  aux_sym__quoted_string_content = 26,
  sym_quoteless_string = 27,
  sym_multiline_string = 28,
  aux_sym_object_repeat1 = 29,
  aux_sym_array_repeat1 = 30,
  aux_sym_multiline_string_repeat1 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [aux_sym_object_token1] = "object_token1",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_escape_sequence] = "escape_sequence",
  [sym_number] = "number",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_null] = "null",
  [sym_comment] = "comment",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [aux_sym__quoted_string_content_token1] = "_quoted_string_content_token1",
  [aux_sym_quoteless_string_token1] = "quoteless_string_token1",
  [anon_sym_SQUOTE_SQUOTE_SQUOTE] = "'''",
  [aux_sym_multiline_string_token1] = "multiline_string_token1",
  [sym_document] = "document",
  [sym__value] = "_value",
  [sym_object] = "object",
  [sym_pair] = "pair",
  [sym_array] = "array",
  [sym_string] = "string",
  [sym_quoted_string] = "quoted_string",
  [aux_sym__quoted_string_content] = "_quoted_string_content",
  [sym_quoteless_string] = "quoteless_string",
  [sym_multiline_string] = "multiline_string",
  [aux_sym_object_repeat1] = "object_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_multiline_string_repeat1] = "multiline_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [aux_sym_object_token1] = aux_sym_object_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_number] = sym_number,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_null] = sym_null,
  [sym_comment] = sym_comment,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym__quoted_string_content_token1] = aux_sym__quoted_string_content_token1,
  [aux_sym_quoteless_string_token1] = aux_sym_quoteless_string_token1,
  [anon_sym_SQUOTE_SQUOTE_SQUOTE] = anon_sym_SQUOTE_SQUOTE_SQUOTE,
  [aux_sym_multiline_string_token1] = aux_sym_multiline_string_token1,
  [sym_document] = sym_document,
  [sym__value] = sym__value,
  [sym_object] = sym_object,
  [sym_pair] = sym_pair,
  [sym_array] = sym_array,
  [sym_string] = sym_string,
  [sym_quoted_string] = sym_quoted_string,
  [aux_sym__quoted_string_content] = aux_sym__quoted_string_content,
  [sym_quoteless_string] = sym_quoteless_string,
  [sym_multiline_string] = sym_multiline_string,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_multiline_string_repeat1] = aux_sym_multiline_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_object_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__quoted_string_content_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoteless_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE_SQUOTE_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_multiline_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__quoted_string_content] = {
    .visible = false,
    .named = false,
  },
  [sym_quoteless_string] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multiline_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 10,
  [15] = 13,
  [16] = 12,
  [17] = 11,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 19,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 21,
  [41] = 38,
  [42] = 39,
  [43] = 20,
  [44] = 22,
  [45] = 45,
  [46] = 31,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 26,
  [51] = 30,
  [52] = 27,
  [53] = 34,
  [54] = 35,
  [55] = 36,
  [56] = 37,
  [57] = 57,
  [58] = 28,
  [59] = 29,
  [60] = 33,
  [61] = 25,
  [62] = 62,
  [63] = 32,
  [64] = 64,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(37);
      ADVANCE_MAP(
        '"', 78,
        '#', 77,
        '\'', 81,
        '.', 28,
        '/', 10,
        '0', 50,
        ':', 45,
        '[', 46,
        '\\', 23,
        ']', 48,
        'f', 14,
        'n', 24,
        't', 20,
        '{', 38,
        '}', 44,
        '+', 13,
        '-', 13,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(35);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 41,
        '"', 78,
        '#', 77,
        '\'', 81,
        ',', 40,
        '.', 111,
        '/', 94,
        '0', 53,
        '[', 46,
        ']', 48,
        'f', 98,
        'n', 107,
        't', 104,
        '{', 38,
        '+', 97,
        '-', 97,
        0x0b, 89,
        '\f', 89,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(54);
      if (lookahead != 0 &&
          (lookahead < '+' || ':' < lookahead) &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(7);
      if (lookahead == '"') ADVANCE(78);
      if (lookahead == '#') ADVANCE(87);
      if (lookahead == '\'') ADVANCE(80);
      if (lookahead == '/') ADVANCE(84);
      if (lookahead == '\\') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(83);
      if (lookahead != 0) ADVANCE(88);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead == '#') ADVANCE(77);
      if (lookahead == ',') ADVANCE(40);
      if (lookahead == '/') ADVANCE(10);
      if (lookahead == ']') ADVANCE(48);
      if (lookahead == '}') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '#') ADVANCE(73);
      if (lookahead == '\'') ADVANCE(8);
      if (lookahead == '/') ADVANCE(118);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(117);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(121);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '\n', 43,
        '"', 78,
        '#', 77,
        '\'', 81,
        ',', 40,
        '.', 111,
        '/', 94,
        '0', 53,
        '}', 44,
        '+', 97,
        '-', 97,
        0x0b, 90,
        '\f', 90,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(54);
      if (lookahead != 0 &&
          (lookahead < '+' || ':' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{') ADVANCE(114);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '"', 78,
        '#', 77,
        '\'', 81,
        '.', 111,
        '/', 94,
        '0', 53,
        '}', 44,
        '+', 97,
        '-', 97,
        0x0b, 92,
        '\f', 92,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(54);
      if (lookahead != 0 &&
          (lookahead < '+' || ':' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{') ADVANCE(114);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(78);
      if (lookahead == '#') ADVANCE(77);
      if (lookahead == '\'') ADVANCE(80);
      if (lookahead == '/') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      END_STATE();
    case 8:
      if (lookahead == '\'') ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '\'') ADVANCE(115);
      END_STATE();
    case 10:
      if (lookahead == '*') ADVANCE(12);
      if (lookahead == '/') ADVANCE(77);
      END_STATE();
    case 11:
      if (lookahead == '*') ADVANCE(11);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == '*') ADVANCE(11);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == '0') ADVANCE(51);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(70);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 21:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 22:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 23:
      ADVANCE_MAP(
        'u', 34,
        '"', 49,
        '\'', 49,
        '/', 49,
        '\\', 49,
        'b', 49,
        'f', 49,
        'n', 49,
        'r', 49,
        't', 49,
      );
      END_STATE();
    case 24:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 25:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 26:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(58);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(60);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(49);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(64);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(30);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(32);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(33);
      END_STATE();
    case 35:
      if (eof) ADVANCE(37);
      ADVANCE_MAP(
        '"', 78,
        '#', 77,
        '\'', 81,
        '.', 28,
        '/', 10,
        '0', 50,
        ':', 45,
        '[', 46,
        ']', 48,
        'f', 14,
        'n', 24,
        't', 20,
        '{', 38,
        '}', 44,
        '+', 13,
        '-', 13,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(35);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 36:
      if (eof) ADVANCE(37);
      ADVANCE_MAP(
        '"', 78,
        '#', 77,
        '\'', 81,
        '.', 111,
        '/', 94,
        '0', 53,
        '[', 46,
        ']', 48,
        'f', 98,
        'n', 107,
        't', 104,
        '{', 38,
        '+', 97,
        '-', 97,
        0x0b, 91,
        '\f', 91,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(36);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(54);
      if (lookahead != 0 &&
          (lookahead < '+' || ':' < lookahead) &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_object_token1);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_object_token1);
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == ',') ADVANCE(40);
      if (lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(89);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_object_token1);
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead == ',') ADVANCE(40);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_object_token1);
      if (lookahead == '\n') ADVANCE(43);
      if (lookahead == ',') ADVANCE(40);
      if (lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(90);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_number);
      ADVANCE_MAP(
        '.', 56,
        'B', 26,
        'b', 26,
        'E', 25,
        'e', 25,
        'O', 27,
        'o', 27,
        'X', 31,
        'x', 31,
      );
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_number);
      ADVANCE_MAP(
        '.', 57,
        'B', 109,
        'b', 109,
        'E', 108,
        'e', 108,
        'O', 110,
        'o', 110,
        'X', 113,
        'x', 113,
      );
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(57);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          (lookahead < '0' || ':' < lookahead) &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(57);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(108);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          (lookahead < '0' || ':' < lookahead) &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          (lookahead < '0' || ':' < lookahead) &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          (lookahead < '0' || ':' < lookahead) &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_true);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_false);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_null);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\r' ||
          lookahead == ',' ||
          lookahead == ':' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(121);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      if (lookahead == '\'') ADVANCE(9);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      if (lookahead == '\'') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym__quoted_string_content_token1);
      if (lookahead == '#') ADVANCE(87);
      if (lookahead == '/') ADVANCE(84);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(83);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(88);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym__quoted_string_content_token1);
      if (lookahead == '*') ADVANCE(86);
      if (lookahead == '/') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(88);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym__quoted_string_content_token1);
      if (lookahead == '*') ADVANCE(85);
      if (lookahead == '/') ADVANCE(88);
      if (lookahead == '\n' ||
          lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\') ADVANCE(12);
      if (lookahead != 0) ADVANCE(86);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym__quoted_string_content_token1);
      if (lookahead == '*') ADVANCE(85);
      if (lookahead == '\n' ||
          lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\') ADVANCE(12);
      if (lookahead != 0) ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym__quoted_string_content_token1);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym__quoted_string_content_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(88);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      ADVANCE_MAP(
        '\n', 41,
        '"', 79,
        '#', 74,
        '\'', 82,
        '.', 111,
        '/', 94,
        '0', 53,
        '[', 47,
        'f', 98,
        'n', 107,
        't', 104,
        '{', 39,
        '\t', 89,
        ' ', 89,
        '+', 97,
        '-', 97,
        0x0b, 89,
        '\f', 89,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(54);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < '+' || ':' < lookahead) &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      ADVANCE_MAP(
        '\n', 43,
        '"', 79,
        '#', 74,
        '\'', 82,
        '.', 111,
        '/', 94,
        '0', 53,
        '\t', 90,
        ' ', 90,
        '+', 97,
        '-', 97,
        '[', 114,
        '{', 114,
        0x0b, 90,
        '\f', 90,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(54);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < '+' || ':' < lookahead) &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      ADVANCE_MAP(
        '"', 79,
        '#', 74,
        '\'', 82,
        '.', 111,
        '/', 94,
        '0', 53,
        '[', 47,
        'f', 98,
        'n', 107,
        't', 104,
        '{', 39,
        '\t', 91,
        ' ', 91,
        '+', 97,
        '-', 97,
        0x0b, 91,
        '\f', 91,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(54);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < '+' || ':' < lookahead) &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      ADVANCE_MAP(
        '"', 79,
        '#', 74,
        '\'', 82,
        '.', 111,
        '/', 94,
        '0', 53,
        '\t', 92,
        ' ', 92,
        '+', 97,
        '-', 97,
        '[', 114,
        '{', 114,
        0x0b, 92,
        '\f', 92,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(54);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < '+' || ':' < lookahead) &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      if (lookahead == '\'') ADVANCE(116);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      if (lookahead == '*') ADVANCE(96);
      if (lookahead == '/') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      ADVANCE_MAP(
        '*', 95,
        '/', 75,
        '\n', 12,
        '\r', 12,
        ',', 12,
        ':', 12,
        ']', 12,
        '}', 12,
      );
      if (lookahead != 0) ADVANCE(96);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      if (lookahead == '*') ADVANCE(95);
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ',' ||
          lookahead == ':' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(12);
      if (lookahead != 0) ADVANCE(96);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      if (lookahead == '0') ADVANCE(55);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          (lookahead < '0' || ':' < lookahead) &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      if (lookahead == 'a') ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      if (lookahead == 'e') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      if (lookahead == 'e') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      if (lookahead == 'l') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      if (lookahead == 'l') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      if (lookahead == 'l') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      if (lookahead == 'r') ADVANCE(106);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      if (lookahead == 's') ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      if (lookahead == 'u') ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      if (lookahead == 'u') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < '+' || '-' < lookahead) &&
          (lookahead < '0' || ':' < lookahead) &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          (lookahead < '0' || ':' < lookahead) &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          (lookahead < '0' || ':' < lookahead) &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          (lookahead < '0' || ':' < lookahead) &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(aux_sym_quoteless_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_SQUOTE_SQUOTE_SQUOTE);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_SQUOTE_SQUOTE_SQUOTE);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(114);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(aux_sym_multiline_string_token1);
      if (lookahead == '#') ADVANCE(73);
      if (lookahead == '/') ADVANCE(118);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(117);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(121);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(aux_sym_multiline_string_token1);
      if (lookahead == '*') ADVANCE(120);
      if (lookahead == '/') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(121);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(aux_sym_multiline_string_token1);
      if (lookahead == '*') ADVANCE(119);
      if (lookahead == '/') ADVANCE(76);
      if (lookahead == '\n' ||
          lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\') ADVANCE(12);
      if (lookahead != 0) ADVANCE(120);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(aux_sym_multiline_string_token1);
      if (lookahead == '*') ADVANCE(119);
      if (lookahead == '\n' ||
          lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\') ADVANCE(12);
      if (lookahead != 0) ADVANCE(120);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(aux_sym_multiline_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(121);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 36},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 36},
  [4] = {.lex_state = 36},
  [5] = {.lex_state = 36},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE_SQUOTE_SQUOTE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(64),
    [sym__value] = STATE(62),
    [sym_object] = STATE(61),
    [sym_array] = STATE(61),
    [sym_string] = STATE(61),
    [sym_quoted_string] = STATE(52),
    [sym_quoteless_string] = STATE(52),
    [sym_multiline_string] = STATE(52),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_number] = ACTIONS(11),
    [sym_true] = ACTIONS(11),
    [sym_false] = ACTIONS(11),
    [sym_null] = ACTIONS(11),
    [sym_comment] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [aux_sym_quoteless_string_token1] = ACTIONS(19),
    [anon_sym_SQUOTE_SQUOTE_SQUOTE] = ACTIONS(21),
  },
  [STATE(2)] = {
    [sym__value] = STATE(49),
    [sym_object] = STATE(25),
    [sym_array] = STATE(25),
    [sym_string] = STATE(25),
    [sym_quoted_string] = STATE(27),
    [sym_quoteless_string] = STATE(27),
    [sym_multiline_string] = STATE(27),
    [anon_sym_LBRACE] = ACTIONS(23),
    [aux_sym_object_token1] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(25),
    [sym_number] = ACTIONS(29),
    [sym_true] = ACTIONS(29),
    [sym_false] = ACTIONS(29),
    [sym_null] = ACTIONS(29),
    [sym_comment] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_SQUOTE] = ACTIONS(33),
    [aux_sym_quoteless_string_token1] = ACTIONS(35),
    [anon_sym_SQUOTE_SQUOTE_SQUOTE] = ACTIONS(37),
  },
  [STATE(3)] = {
    [sym__value] = STATE(39),
    [sym_object] = STATE(25),
    [sym_array] = STATE(25),
    [sym_string] = STATE(25),
    [sym_quoted_string] = STATE(27),
    [sym_quoteless_string] = STATE(27),
    [sym_multiline_string] = STATE(27),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(39),
    [sym_number] = ACTIONS(29),
    [sym_true] = ACTIONS(29),
    [sym_false] = ACTIONS(29),
    [sym_null] = ACTIONS(29),
    [sym_comment] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_SQUOTE] = ACTIONS(33),
    [aux_sym_quoteless_string_token1] = ACTIONS(35),
    [anon_sym_SQUOTE_SQUOTE_SQUOTE] = ACTIONS(37),
  },
  [STATE(4)] = {
    [sym__value] = STATE(42),
    [sym_object] = STATE(25),
    [sym_array] = STATE(25),
    [sym_string] = STATE(25),
    [sym_quoted_string] = STATE(27),
    [sym_quoteless_string] = STATE(27),
    [sym_multiline_string] = STATE(27),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(41),
    [sym_number] = ACTIONS(29),
    [sym_true] = ACTIONS(29),
    [sym_false] = ACTIONS(29),
    [sym_null] = ACTIONS(29),
    [sym_comment] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_SQUOTE] = ACTIONS(33),
    [aux_sym_quoteless_string_token1] = ACTIONS(35),
    [anon_sym_SQUOTE_SQUOTE_SQUOTE] = ACTIONS(37),
  },
  [STATE(5)] = {
    [sym__value] = STATE(47),
    [sym_object] = STATE(25),
    [sym_array] = STATE(25),
    [sym_string] = STATE(25),
    [sym_quoted_string] = STATE(27),
    [sym_quoteless_string] = STATE(27),
    [sym_multiline_string] = STATE(27),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
    [sym_true] = ACTIONS(29),
    [sym_false] = ACTIONS(29),
    [sym_null] = ACTIONS(29),
    [sym_comment] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_SQUOTE] = ACTIONS(33),
    [aux_sym_quoteless_string_token1] = ACTIONS(35),
    [anon_sym_SQUOTE_SQUOTE_SQUOTE] = ACTIONS(37),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      aux_sym_quoteless_string_token1,
    ACTIONS(21), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(45), 1,
      sym_number,
    STATE(48), 1,
      sym_pair,
    STATE(57), 1,
      sym_string,
    ACTIONS(43), 2,
      aux_sym_object_token1,
      anon_sym_RBRACE,
    STATE(52), 3,
      sym_quoted_string,
      sym_quoteless_string,
      sym_multiline_string,
  [34] = 10,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      aux_sym_quoteless_string_token1,
    ACTIONS(21), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(45), 1,
      sym_number,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    STATE(38), 1,
      sym_pair,
    STATE(57), 1,
      sym_string,
    STATE(52), 3,
      sym_quoted_string,
      sym_quoteless_string,
      sym_multiline_string,
  [67] = 10,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      aux_sym_quoteless_string_token1,
    ACTIONS(21), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(45), 1,
      sym_number,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(41), 1,
      sym_pair,
    STATE(57), 1,
      sym_string,
    STATE(52), 3,
      sym_quoted_string,
      sym_quoteless_string,
      sym_multiline_string,
  [100] = 5,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(51), 1,
      sym_escape_sequence,
    ACTIONS(56), 1,
      aux_sym__quoted_string_content_token1,
    STATE(9), 1,
      aux_sym__quoted_string_content,
    ACTIONS(54), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [117] = 5,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(59), 1,
      sym_escape_sequence,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 1,
      aux_sym__quoted_string_content_token1,
    STATE(12), 1,
      aux_sym__quoted_string_content,
  [133] = 5,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_escape_sequence,
    ACTIONS(67), 1,
      anon_sym_SQUOTE,
    ACTIONS(69), 1,
      aux_sym__quoted_string_content_token1,
    STATE(9), 1,
      aux_sym__quoted_string_content,
  [149] = 5,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_escape_sequence,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      aux_sym__quoted_string_content_token1,
    STATE(9), 1,
      aux_sym__quoted_string_content,
  [165] = 5,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(61), 1,
      anon_sym_SQUOTE,
    ACTIONS(71), 1,
      sym_escape_sequence,
    ACTIONS(73), 1,
      aux_sym__quoted_string_content_token1,
    STATE(11), 1,
      aux_sym__quoted_string_content,
  [181] = 5,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(75), 1,
      sym_escape_sequence,
    ACTIONS(77), 1,
      anon_sym_DQUOTE,
    ACTIONS(79), 1,
      aux_sym__quoted_string_content_token1,
    STATE(16), 1,
      aux_sym__quoted_string_content,
  [197] = 5,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_SQUOTE,
    ACTIONS(81), 1,
      sym_escape_sequence,
    ACTIONS(83), 1,
      aux_sym__quoted_string_content_token1,
    STATE(17), 1,
      aux_sym__quoted_string_content,
  [213] = 5,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_escape_sequence,
    ACTIONS(69), 1,
      aux_sym__quoted_string_content_token1,
    ACTIONS(85), 1,
      anon_sym_DQUOTE,
    STATE(9), 1,
      aux_sym__quoted_string_content,
  [229] = 5,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_escape_sequence,
    ACTIONS(69), 1,
      aux_sym__quoted_string_content_token1,
    ACTIONS(85), 1,
      anon_sym_SQUOTE,
    STATE(9), 1,
      aux_sym__quoted_string_content,
  [245] = 4,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(87), 1,
      aux_sym_object_token1,
    ACTIONS(90), 1,
      anon_sym_RBRACE,
    STATE(18), 1,
      aux_sym_object_repeat1,
  [258] = 4,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(92), 1,
      aux_sym_object_token1,
    ACTIONS(94), 1,
      anon_sym_RBRACK,
    STATE(45), 1,
      aux_sym_array_repeat1,
  [271] = 4,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(98), 1,
      aux_sym_multiline_string_token1,
    STATE(24), 1,
      aux_sym_multiline_string_repeat1,
  [284] = 4,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(102), 1,
      aux_sym_multiline_string_token1,
    STATE(20), 1,
      aux_sym_multiline_string_repeat1,
  [297] = 4,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(104), 1,
      aux_sym_object_token1,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    STATE(18), 1,
      aux_sym_object_repeat1,
  [310] = 4,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(92), 1,
      aux_sym_object_token1,
    ACTIONS(108), 1,
      anon_sym_RBRACK,
    STATE(45), 1,
      aux_sym_array_repeat1,
  [323] = 4,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(110), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(112), 1,
      aux_sym_multiline_string_token1,
    STATE(24), 1,
      aux_sym_multiline_string_repeat1,
  [336] = 3,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(115), 1,
      aux_sym_object_token1,
    ACTIONS(117), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [347] = 3,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(119), 1,
      aux_sym_object_token1,
    ACTIONS(121), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [358] = 3,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(123), 1,
      aux_sym_object_token1,
    ACTIONS(125), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [369] = 3,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(127), 1,
      aux_sym_object_token1,
    ACTIONS(129), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [380] = 3,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(131), 1,
      aux_sym_object_token1,
    ACTIONS(133), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [391] = 3,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(135), 1,
      aux_sym_object_token1,
    ACTIONS(137), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [402] = 3,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(139), 1,
      aux_sym_object_token1,
    ACTIONS(141), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [413] = 3,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(143), 1,
      aux_sym_object_token1,
    ACTIONS(145), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [424] = 3,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(147), 1,
      aux_sym_object_token1,
    ACTIONS(149), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [435] = 3,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(151), 1,
      aux_sym_object_token1,
    ACTIONS(153), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [446] = 3,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(155), 1,
      aux_sym_object_token1,
    ACTIONS(157), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [457] = 3,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(159), 1,
      aux_sym_object_token1,
    ACTIONS(161), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [468] = 3,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(163), 1,
      aux_sym_object_token1,
    ACTIONS(165), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [479] = 4,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(104), 1,
      aux_sym_object_token1,
    ACTIONS(167), 1,
      anon_sym_RBRACE,
    STATE(22), 1,
      aux_sym_object_repeat1,
  [492] = 4,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(92), 1,
      aux_sym_object_token1,
    ACTIONS(169), 1,
      anon_sym_RBRACK,
    STATE(23), 1,
      aux_sym_array_repeat1,
  [505] = 4,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(173), 1,
      aux_sym_multiline_string_token1,
    STATE(43), 1,
      aux_sym_multiline_string_repeat1,
  [518] = 4,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(104), 1,
      aux_sym_object_token1,
    ACTIONS(175), 1,
      anon_sym_RBRACE,
    STATE(44), 1,
      aux_sym_object_repeat1,
  [531] = 4,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(92), 1,
      aux_sym_object_token1,
    ACTIONS(177), 1,
      anon_sym_RBRACK,
    STATE(19), 1,
      aux_sym_array_repeat1,
  [544] = 4,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(98), 1,
      aux_sym_multiline_string_token1,
    ACTIONS(179), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    STATE(24), 1,
      aux_sym_multiline_string_repeat1,
  [557] = 4,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(104), 1,
      aux_sym_object_token1,
    ACTIONS(181), 1,
      anon_sym_RBRACE,
    STATE(18), 1,
      aux_sym_object_repeat1,
  [570] = 4,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(183), 1,
      aux_sym_object_token1,
    ACTIONS(186), 1,
      anon_sym_RBRACK,
    STATE(45), 1,
      aux_sym_array_repeat1,
  [583] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 2,
      ts_builtin_sym_end,
      anon_sym_COLON,
  [591] = 3,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(188), 1,
      aux_sym_object_token1,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
  [601] = 3,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_RBRACE,
    ACTIONS(192), 1,
      aux_sym_object_token1,
  [611] = 3,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_RBRACK,
    ACTIONS(194), 1,
      aux_sym_object_token1,
  [621] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 2,
      ts_builtin_sym_end,
      anon_sym_COLON,
  [629] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 2,
      ts_builtin_sym_end,
      anon_sym_COLON,
  [637] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 2,
      ts_builtin_sym_end,
      anon_sym_COLON,
  [645] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 2,
      ts_builtin_sym_end,
      anon_sym_COLON,
  [653] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 2,
      ts_builtin_sym_end,
      anon_sym_COLON,
  [661] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      ts_builtin_sym_end,
  [668] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      ts_builtin_sym_end,
  [675] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      anon_sym_COLON,
  [682] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
  [689] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
  [696] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
  [703] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
  [710] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      ts_builtin_sym_end,
  [717] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      ts_builtin_sym_end,
  [724] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 34,
  [SMALL_STATE(8)] = 67,
  [SMALL_STATE(9)] = 100,
  [SMALL_STATE(10)] = 117,
  [SMALL_STATE(11)] = 133,
  [SMALL_STATE(12)] = 149,
  [SMALL_STATE(13)] = 165,
  [SMALL_STATE(14)] = 181,
  [SMALL_STATE(15)] = 197,
  [SMALL_STATE(16)] = 213,
  [SMALL_STATE(17)] = 229,
  [SMALL_STATE(18)] = 245,
  [SMALL_STATE(19)] = 258,
  [SMALL_STATE(20)] = 271,
  [SMALL_STATE(21)] = 284,
  [SMALL_STATE(22)] = 297,
  [SMALL_STATE(23)] = 310,
  [SMALL_STATE(24)] = 323,
  [SMALL_STATE(25)] = 336,
  [SMALL_STATE(26)] = 347,
  [SMALL_STATE(27)] = 358,
  [SMALL_STATE(28)] = 369,
  [SMALL_STATE(29)] = 380,
  [SMALL_STATE(30)] = 391,
  [SMALL_STATE(31)] = 402,
  [SMALL_STATE(32)] = 413,
  [SMALL_STATE(33)] = 424,
  [SMALL_STATE(34)] = 435,
  [SMALL_STATE(35)] = 446,
  [SMALL_STATE(36)] = 457,
  [SMALL_STATE(37)] = 468,
  [SMALL_STATE(38)] = 479,
  [SMALL_STATE(39)] = 492,
  [SMALL_STATE(40)] = 505,
  [SMALL_STATE(41)] = 518,
  [SMALL_STATE(42)] = 531,
  [SMALL_STATE(43)] = 544,
  [SMALL_STATE(44)] = 557,
  [SMALL_STATE(45)] = 570,
  [SMALL_STATE(46)] = 583,
  [SMALL_STATE(47)] = 591,
  [SMALL_STATE(48)] = 601,
  [SMALL_STATE(49)] = 611,
  [SMALL_STATE(50)] = 621,
  [SMALL_STATE(51)] = 629,
  [SMALL_STATE(52)] = 637,
  [SMALL_STATE(53)] = 645,
  [SMALL_STATE(54)] = 653,
  [SMALL_STATE(55)] = 661,
  [SMALL_STATE(56)] = 668,
  [SMALL_STATE(57)] = 675,
  [SMALL_STATE(58)] = 682,
  [SMALL_STATE(59)] = 689,
  [SMALL_STATE(60)] = 696,
  [SMALL_STATE(61)] = 703,
  [SMALL_STATE(62)] = 710,
  [SMALL_STATE(63)] = 717,
  [SMALL_STATE(64)] = 724,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_object_repeat1, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__quoted_string_content, 2, 0, 0), SHIFT_REPEAT(9),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__quoted_string_content, 2, 0, 0),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__quoted_string_content, 2, 0, 0), SHIFT_REPEAT(9),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_multiline_string_repeat1, 2, 0, 0),
  [112] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_multiline_string_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__value, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoteless_string, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoteless_string, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_string, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_string, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiline_string, 2, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_string, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_string, 3, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiline_string, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 4, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 4, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 1),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pair, 3, 0, 1),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hjson(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
